[wip] feat: support predis
godruoyi/php-snowflake pull request #72
Opened 2024-04-06 15:31 UTC by godruoyi

2024-04-06 15:38 UTC, godruoyi commented on composer.json
> +        "predis/predis": "^2.0"
self-review: remove this from composer.json, if the user wants to use PHPRedisSequenceResolver then they should install this extension manually

2024-04-06 15:55 UTC, Bilge requested changes
I couldn't help but notice this does not follow my suggestion to use the adapter pattern, but instead implements an entirely separate `SequenceResolver`. I still think the adapter pattern would work better, unless you have some specific reason why you disagree?

2024-04-06 15:55 UTC, Bilge commented on src/PHPRedisSequenceResolver.php
> +LUA;
This looks ugly aligned along the hard-left edge, but could (and should) be indented two tab stops with [flexible heredoc syntax](https://wiki.php.net/rfc/flexible_heredoc_nowdoc_syntaxes) (supported since PHP 7.3). Applies throughout this PR.

```suggestion
        if redis.call('set', KEYS[1], ARGV[1], "EX", ARGV[2], "NX") then
            return 0
        else
            return redis.call('incr', KEYS[1])
        end
        LUA;
```

2024-04-06 15:55 UTC, Bilge commented on composer.json
> +        "predis/predis": "^2.0"
Seems fine to me, if it remains under `require-dev`; does not affect the user.

2024-04-06 15:55 UTC, Bilge commented on composer.json
> +        "pint": "vendor/bin/pint --config ./pint.json"
`./` has no meaning here.

```suggestion
        "pint": "vendor/bin/pint --config pint.json"
```

2024-04-06 15:55 UTC, Bilge commented on src/PHPRedisSequenceResolver.php
> +class PHPRedisSequenceResolver implements SequenceResolver
This should probably be called _PhpRedisSequenceResolver_, in line with the [proposed naming guidelines for acronyms in PHP](https://wiki.php.net/rfc/class-naming-acronyms) (and the naming guidelines for other major object-oriented frameworks, such as .NET). However, the thought occurs that this is not for a generic PHP-Redis library, this is specifically for _Predis_, which is just called _Predis_, not _PHP Redis_ (even if that is where the name originally came from). As such, this should probably be called _PredisSequenceResolver_, for clarity.

2024-04-06 15:55 UTC, Bilge commented on src/RedisSequenceResolver.php
> +LUA;
This entire block is duplicated. In the interests of maintainability, it should be hoisted to a shared location, probably as a public constant of some other class or interface.

2024-04-07 04:55 UTC, godruoyi commented on composer.json
> +        "predis/predis": "^2.0"
Actually, we shouldn't include it in composer.json because not all users utilize phpredis. If a user wants to use the phpredis resolver, they will need to install it manually.

2024-04-07 05:04 UTC, godruoyi commented on src/RedisSequenceResolver.php
> +LUA;
We opted not to include extra classes/functions for this purpose, which is why we developed a separate phpredisresolver instead of utilizing a Redis adapter or interface. This package is designed to be straightforward, and I prefer avoiding excessive design complexity. Consequently, I find it acceptable to have some duplicated code. Additionally, I want to avoid introducing any disruptive changes by implementing a new interface or adapter that would require frequent major version releases.

2024-04-07 07:37 UTC, Bilge commented on composer.json
> +        "predis/predis": "^2.0"
`require-dev` does not affect the library consumer. Nothing from this section is installed.

2024-04-08 04:02 UTC, godruoyi commented on composer.json
> +        "predis/predis": "^2.0"
thank you @Bilge for letting me know, I will update this in the next PR.

2024-04-08 04:11 UTC, merged

2024-04-08 05:24 UTC, godruoyi commented on composer.json
> +        "predis/predis": "^2.0"
https://github.com/godruoyi/php-snowflake/pull/73